<?php
/**
 * @category   Bluethink
 * @package    Bluethink_CustomCatalog
 * @author     santosh.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bluethink\CustomCatalog\Block;

use Magento\Framework\View\Element\Template\Context;
use Bluethink\CustomCatalog\Model\CustomCatalogFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * CustomCatalog View block
 */
class CustomCatalogView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var CustomCatalog
     */
    protected $_customcatalog;
    public function __construct(
        Context $context,
        CustomCatalogFactory $customcatalog,
        FilterProvider $filterProvider
    ) {
        $this->_customcatalog = $customcatalog;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Bluethink CustomCatalog Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $customcatalog = $this->_customcatalog->create();
        $singleData = $customcatalog->load($id);
        if($singleData->getCustomCatalogId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}